# Generated by Django 4.2.5 on 2023-09-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_audiofile_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='audio_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
